version: "3.8"

services:
  db:
    image: postgres:14
    container_name: library_db
    environment:
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=libraryuser
      - POSTGRES_PASSWORD=library123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U libraryuser -d librarydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library_network

  backend:
    build: ./backend
    container_name: library-backend
    environment:
      - DEBUG=False
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=libraryuser
      - POSTGRES_PASSWORD=library123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - library_network

  frontend:
    build: ./frontend
    container_name: library-frontend
    environment:
      - API_URL="http://backend:8000/api"
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - library_network

networks:
  library_network:
    driver: bridge

volumes:
  postgres_data:
