apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: library-namespace
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,backend,frontend,django-service,streamlit-service"
  CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1,http://django-service:8000,http://streamlit-service:8501"
  CORS_ALLOWED_ORIGINS: "http://localhost:8501,http://127.0.0.1:8501,http://streamlit-service:8501"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: library-namespace
  labels:
    app: django-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django-app
          image: ivica650/library-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: ALLOWED_HOSTS
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: CSRF_TRUSTED_ORIGINS
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: CORS_ALLOWED_ORIGINS
            - name: CORS_ALLOW_CREDENTIALS
              value: "True"

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: library-namespace
spec:
  selector:
    app: django-backend
  ports:
    - port: 8000
      targetPort: 8000
